{"uuid":"fab83809-5607-431c-ad7e-12bcbeb2acac","name":"127.0.0.1:62025","children":["f49a4e58-aef2-4c27-84a0-e51345e73a52","5af6db21-9fed-40e1-bf49-26cdba8a51a9","54392c3e-89b7-42a4-85c6-0526366ee15e","1860408f-7cb5-4efb-817b-2ff985b85d1c","64b815f2-6687-416d-b29b-93a2878c247f","2463e27a-80cc-4c0b-84eb-078d2a21a3eb","85bbe8c0-65c4-41a3-9951-d5e6f1e9e553"],"befores":[{"name":"startServer","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Invalid server instance exception has occured: There is no installed nodes! Please install node via NPM (https://www.npmjs.com/package/appium#using-node-js) or download and install Appium app (http://appium.io/downloads.html)","trace":"io.appium.java_client.service.local.InvalidServerInstanceException: Invalid server instance exception has occured: There is no installed nodes! Please install node via NPM (https://www.npmjs.com/package/appium#using-node-js) or download and install Appium app (http://appium.io/downloads.html)\r\n\tat io.appium.java_client.service.local.AppiumServiceBuilder.findNodeInCurrentFileSystem(AppiumServiceBuilder.java:184)\r\n\tat io.appium.java_client.service.local.AppiumServiceBuilder.checkAppiumJS(AppiumServiceBuilder.java:345)\r\n\tat io.appium.java_client.service.local.AppiumServiceBuilder.createArgs(AppiumServiceBuilder.java:425)\r\n\tat org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:358)\r\n\tat com.crazy.auto.driver.AppiumServers.startServer(AppiumServers.java:56)\r\n\tat com.crazy.auto.test.DouBanTestBase0611.startServer(DouBanTestBase0611.java:33)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:498)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)\r\n\tat org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)\r\n\tat org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)\r\n\tat org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)\r\n\tat org.testng.TestRunner.beforeRun(TestRunner.java:529)\r\n\tat org.testng.TestRunner.run(TestRunner.java:497)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:455)\r\n\tat org.testng.SuiteRunner.access$000(SuiteRunner.java:40)\r\n\tat org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)\r\n\tat org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)\r\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\r\n\tat java.lang.Thread.run(Thread.java:745)\r\nCaused by: java.io.IOException: D:\\nodejs\\npm_modules\\node_modules\n\n┌────────────────────────────────────────────────────────────┐\n│                  npm update check failed                   │\n│            Try running with sudo or get access             │\n│            to the local update config store via            │\n│ sudo chown -R $USER:$(id -gn $USER) C:\\Users\\lixio\\.config │\n└────────────────────────────────────────────────────────────┘\n\r\n\tat io.appium.java_client.service.local.AppiumServiceBuilder.findNodeInCurrentFileSystem(AppiumServiceBuilder.java:185)\r\n\t... 24 more\r\n"},"stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1592036441993,"stop":1592036445231}],"afters":[],"links":[],"start":1592036441964,"stop":1592036445645}